version: "3.0"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      dnsmasq_cloudflared_net:
        ipv4_address: 10.0.0.2

  dnsmasq:
    container_name: dnsmasq
    image: dnsmasq
    command: --server=10.0.0.2#5054 --no-resolv --no-hosts --log-facility=-
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      dnsmasq_cloudflared_net:
        ipv4_address: 10.0.0.3

networks:
  dnsmasq_cloudflared_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
